name: Publish version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package on npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Draft Github release with archive
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          body: |
            ### :warning: Breaking changes

            ### :bulb: Features

            ### :beetle: Bug fixes

            ### :wrench: Technical
